/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ServicesServiceKeyRouteImport } from './routes/services.$serviceKey'
import { Route as AboutTeamRouteImport } from './routes/about.team'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceKeyRoute = ServicesServiceKeyRouteImport.update({
  id: '/services/$serviceKey',
  path: '/services/$serviceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/about/team': typeof AboutTeamRoute
  '/services/$serviceKey': typeof ServicesServiceKeyRoute
  '/about/': typeof AboutIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/about/team': typeof AboutTeamRoute
  '/services/$serviceKey': typeof ServicesServiceKeyRoute
  '/about': typeof AboutIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/about/team': typeof AboutTeamRoute
  '/services/$serviceKey': typeof ServicesServiceKeyRoute
  '/about/': typeof AboutIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/about/team'
    | '/services/$serviceKey'
    | '/about/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/about/team'
    | '/services/$serviceKey'
    | '/about'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/about/team'
    | '/services/$serviceKey'
    | '/about/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  AboutTeamRoute: typeof AboutTeamRoute
  ServicesServiceKeyRoute: typeof ServicesServiceKeyRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceKey': {
      id: '/services/$serviceKey'
      path: '/services/$serviceKey'
      fullPath: '/services/$serviceKey'
      preLoaderRoute: typeof ServicesServiceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  AboutTeamRoute: AboutTeamRoute,
  ServicesServiceKeyRoute: ServicesServiceKeyRoute,
  AboutIndexRoute: AboutIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
